### ISSUE TITLE
USER STORY: <View products catalog>

### ISSUE THREAD

**Issue by EL1909** [EL1909/adela_valverde#3]
As a **Visitor** I can **See all products and services provides by Adela** so that **i can purchase or acquire the service**

## Acceptance Criteria:
- Acceptance Criteria 1: View products catalog.
- Acceptance Criteria 2: View diferente categories.
- Acceptance Criteria 3: View products specification within product selection.

## Tasks
- [x] Create products model.
- [x] Create templates for all product and individual products.
- [ ] Defines vales to be showed for each product.
