### ISSUE TITLE
USER STORY: <View main offers>

### ISSUE THREAD

**Issue by EL1909** [EL1909/adela_valverde#4]
As a **Visitor** I can **Watch one product in the home page** so that **I can easily access without surfing the site**

## Tasks
- [x] Create .div above home body
- [x] Assign desired link to access a product
- [ ] Add capacity to view more than one product by moving to the sides
