### ISSUE TITLE
USER STORY: <Review Adela's Background>

### ISSUE THREAD

**Issue by EL1909** [EL1909/adela_valverde#5]
As a **user** I can **review Adela's background** so that ** i'm aware of her biography and other informations she wants to share**

## Acceptance Criteria:
- Create Key Moments Module
- Acceptance Criteria 2: 
- Acceptance Criteria 3: 

## Tasks
- [x] Create Key Moments Module
- [x] Setup CRUD operations for Key Moments Module
- [x] Setup user permissions for KM activities
